name: build-ip-guard

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -q -DskipTests package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ip-guard-3.5.1
          path: target/ip-guard.jar
